import type { AnalysisResult, SprintPlan, SprintTask } from "@/types";

const EMOJI: Record<string, string> = {
  Critical: "🔴",
  High: "🟠",
  Medium: "🟡",
  Low: "🟢",
};

function taskLine(t: SprintTask, withHours = true): string {
  return withHours
    ? `- [ ] #${t.issue_number} - ${t.title} (~${t.estimated_hours}h)`
    : `- [ ] #${t.issue_number} - ${t.title}`;
}

export function buildMarkdownReport(
  result: AnalysisResult,
  plan: SprintPlan | null,
): string {
  const date = new Date().toISOString().slice(0, 10);
  const counts = { Critical: 0, High: 0, Medium: 0, Low: 0 } as Record<string, number>;
  for (const i of result.issues) counts[i.ai_analysis.priority] = (counts[i.ai_analysis.priority] ?? 0) + 1;

  const lines: string[] = [];
  lines.push(`# BugWhisperer Analysis Report`, ``);
  lines.push(`## Repository: ${result.repo}`);
  lines.push(`## Generated: ${date}`);
  lines.push(`## Total Issues Analyzed: ${result.total_issues}`, ``, `---`, ``);
  lines.push(`## Priority Summary`, ``);
  lines.push(`- 🔴 Critical: ${counts.Critical} issues`);
  lines.push(`- 🟠 High: ${counts.High} issues`);
  lines.push(`- 🟡 Medium: ${counts.Medium} issues`);
  lines.push(`- 🟢 Low: ${counts.Low} issues`, ``, `---`, ``);
  lines.push(`## Issue Details`, ``);
  for (const i of result.issues) {
    const a = i.ai_analysis;
    lines.push(`### #${i.number} - ${i.title}`);
    lines.push(
      `${EMOJI[a.priority] ?? ""} **Priority:** ${a.priority} | **Complexity:** ${a.complexity}`,
    );
    lines.push(``, `**Root Cause:** ${a.root_cause}`, ``);
    lines.push(`**Suggested Fix:** ${a.suggested_fix}`, ``, `---`, ``);
  }

  if (plan) {
    lines.push(`## Recommended Sprint Plan`, ``);
    lines.push(`**Sprint Goal:** ${plan.sprint_goal}`, ``);
    lines.push(
      `**Total Estimated Hours:** ${plan.total_estimated_hours} | **Team Size:** ${plan.team_size_recommended}`,
      ``,
    );
    lines.push(`### Week 1`);
    plan.week_1.forEach((t) => lines.push(taskLine(t)));
    lines.push(``, `### Week 2`);
    plan.week_2.forEach((t) => lines.push(taskLine(t)));
    lines.push(``, `### Backlog`);
    plan.backlog.forEach((t) => lines.push(taskLine(t, false)));
    lines.push(``, `---`, ``);
  }

  lines.push(`*Generated by BugWhisperer - AI GitHub Issue Analyzer*`);
  lines.push(`*Powered by Groq AI (Llama 3.1)*`);
  return lines.join("\n");
}

export function downloadMarkdownReport(
  result: AnalysisResult,
  plan: SprintPlan | null,
) {
  const md = buildMarkdownReport(result, plan);
  const date = new Date().toISOString().slice(0, 10);
  const slug = result.repo.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `bugwhisperer-${slug}-${date}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}